name: Integration - Go

on:
  schedule:
    # Run the ci on the latest commit of master every day at 4:00 am
    - cron:  '00 04 * * *'
    
jobs:    
  be1-go:
    name: Be1-Go
    runs-on: ubuntu-latest

    steps:
      - name: Use go >= 1.19
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19"

      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build
        if: ${{ always() }} # execute even if previous steps failed
        working-directory: ./be1-go
        run: |
          make build
        
      - name: Run Karate tests
        working-directory: ./tests/karate
        run: mvn test -DargLine=-Dkarate.env=go -Dtest=BackEndTest#fullTest
        
      - name: Publish HTML Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Go HTML Report
          path: ./tests/karate/target/karate-reports
                  
      - name: Publish Cucumber Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Go Cucumber Report
          path: ./tests/karate/target/cucumber-html-reports
          
      - name: Publish Server logs
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Go Server Logs
          path: ./tests/karate/go.log
