name: Integration - Scala

on:
  schedule:
    # Run the ci on the latest commit of master every day at 4:00 am
    - cron:  '00 04 * * *'
    
jobs:
  be2-scala:
    name: Be2-Scala
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile server
        working-directory: ./be2-scala
        run: sbt compile
        
      - name: Assemble server jar file
        working-directory: ./be2-scala
        run: sbt assembly
        
      - name: Run Karate tests
        working-directory: ./tests/karate
        run: mvn test -DargLine=-Dkarate.env=scala -Dtest=BackEndTest#fullTest
        
      - name: Publish HTML Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Scala HTML Report
          path: ./tests/karate/target/karate-reports
                  
      - name: Publish Cucumber Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Scala Cucumber Report
          path: ./tests/karate/target/cucumber-html-reports
          
      - name: Publish Server logs
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Scala Server Logs
          path: ./tests/karate/scala.log
