name: Integration Tests

on:
  schedule:
    # Run the ci every day at 19:00
    - cron:  '00 19 * * *'
    
jobs:
  be2-scala:
    name: Be2-Scala
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis

      - name: Compile server
        working-directory: ./be2-scala
        run: sbt compile
        
      - name: Assemble server jar file
        working-directory: ./be2-scala
        run: sbt assembly
        
      - name: Run Karate tests
        working-directory: ./tests/karate
        run: mvn test -DargLine=-Dkarate.env=scala -Dtest=BackEndTest#fullTest
        
      - name: Publish HTML Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Scala HTML Report
          path: ./tests/karate/target/karate-reports
                  
      - name: Publish Cucumber Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Scala Cucumber Report
          path: ./tests/karate/target/cucumber-html-reports
          
      - name: Publish Server logs
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Scala Server Logs
          path: ./tests/karate/scala.log
          
  be1-go:
    name: Be1-Go
    runs-on: ubuntu-latest

    steps:
      - name: Use go >= 1.19
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19"

      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis

      - uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build
        if: ${{ always() }} # execute even if previous steps failed
        working-directory: ./be1-go
        run: |
          make build
        
      - name: Run Karate tests
        working-directory: ./tests/karate
        run: mvn test -DargLine=-Dkarate.env=go -Dtest=BackEndTest#fullTest
        
      - name: Publish HTML Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Go HTML Report
          path: ./tests/karate/target/karate-reports
                  
      - name: Publish Cucumber Report
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Go Cucumber Report
          path: ./tests/karate/target/cucumber-html-reports
          
      - name: Publish Server logs
        if: ${{ always() }} # execute even if previous steps failed
        uses: actions/upload-artifact@v3
        with:
          name: Go Server Logs
          path: ./tests/karate/go.log
